<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Currency;
use Illuminate\Support\Facades\DB;
class CurrencySeeder extends Seeder
{
    public function run()
    {
        DB::table('currencies')->truncate();

        Currency::insert([
            // ===== ACTIVE CURRENCIES =====
            [
                'code' => 'VND',
                'name' => 'Vietnamese Dong',
                'symbol' => '₫',
                'locale' => 'vi',
                'exchange_rate' => 1,
                'decimal_places' => 0,
                'position' => 'right',
                'is_default' => true,
                'is_active' => true,
            ],
            [
                'code' => 'USD',
                'name' => 'US Dollar',
                'symbol' => '$',
                'locale' => 'en',
                'exchange_rate' => 25000,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => true,
            ],
            [
                'code' => 'JPY',
                'name' => 'Japanese Yen',
                'symbol' => '¥',
                'locale' => 'ja',
                'exchange_rate' => 170,
                'decimal_places' => 0,
                'position' => 'left',
                'is_default' => false,
                'is_active' => true,
            ],
            [
                'code' => 'RUB',
                'name' => 'Russian Ruble',
                'symbol' => '₽',
                'locale' => 'ru',
                'exchange_rate' => 280,
                'decimal_places' => 2,
                'position' => 'right',
                'is_default' => false,
                'is_active' => true,
            ],

            // ===== INACTIVE CURRENCIES =====
            [
                'code' => 'EUR',
                'name' => 'Euro',
                'symbol' => '€',
                'locale' => 'de',
                'exchange_rate' => 27000,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'GBP',
                'name' => 'British Pound',
                'symbol' => '£',
                'locale' => 'en-gb',
                'exchange_rate' => 31500,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'CAD',
                'name' => 'Canadian Dollar',
                'symbol' => 'C$',
                'locale' => 'en-ca',
                'exchange_rate' => 18500,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'AUD',
                'name' => 'Australian Dollar',
                'symbol' => 'A$',
                'locale' => 'en-au',
                'exchange_rate' => 16500,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'CHF',
                'name' => 'Swiss Franc',
                'symbol' => 'Fr.',
                'locale' => 'de-ch',
                'exchange_rate' => 28500,
                'decimal_places' => 2,
                'position' => 'right',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'CNY',
                'name' => 'Chinese Yuan',
                'symbol' => '¥',
                'locale' => 'zh',
                'exchange_rate' => 3500,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'KRW',
                'name' => 'South Korean Won',
                'symbol' => '₩',
                'locale' => 'ko',
                'exchange_rate' => 19,
                'decimal_places' => 0,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'SGD',
                'name' => 'Singapore Dollar',
                'symbol' => 'S$',
                'locale' => 'en-sg',
                'exchange_rate' => 18500,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'THB',
                'name' => 'Thai Baht',
                'symbol' => '฿',
                'locale' => 'th',
                'exchange_rate' => 720,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'MYR',
                'name' => 'Malaysian Ringgit',
                'symbol' => 'RM',
                'locale' => 'ms',
                'exchange_rate' => 5400,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'IDR',
                'name' => 'Indonesian Rupiah',
                'symbol' => 'Rp',
                'locale' => 'id',
                'exchange_rate' => 1.6,
                'decimal_places' => 0,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'PHP',
                'name' => 'Philippine Peso',
                'symbol' => '₱',
                'locale' => 'tl',
                'exchange_rate' => 450,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'INR',
                'name' => 'Indian Rupee',
                'symbol' => '₹',
                'locale' => 'hi',
                'exchange_rate' => 300,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'BRL',
                'name' => 'Brazilian Real',
                'symbol' => 'R$',
                'locale' => 'pt',
                'exchange_rate' => 5100,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'MXN',
                'name' => 'Mexican Peso',
                'symbol' => '$',
                'locale' => 'es',
                'exchange_rate' => 1450,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'ZAR',
                'name' => 'South African Rand',
                'symbol' => 'R',
                'locale' => 'af',
                'exchange_rate' => 1350,
                'decimal_places' => 2,
                'position' => 'right',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'TRY',
                'name' => 'Turkish Lira',
                'symbol' => '₺',
                'locale' => 'tr',
                'exchange_rate' => 780,
                'decimal_places' => 2,
                'position' => 'right',
                'is_default' => false,
                'is_active' => false,
            ],
            [
                'code' => 'EGP',
                'name' => 'Egyptian Pound',
                'symbol' => '£',
                'locale' => 'ar',
                'exchange_rate' => 520,
                'decimal_places' => 2,
                'position' => 'left',
                'is_default' => false,
                'is_active' => false,
            ],
        ]);
    }

}
